apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: cve-web
  name: cve-web
spec:
  # keep it simmple use Nodeport to map it to running node
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 32080
  selector:
    io.kompose.service: cve-web
status:
  loadBalancer: {}
