apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: cve-poc
  name: cve-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cve-poc
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/cve-net: "true"
        io.kompose.service: cve-poc
    spec:
      containers:
        - env:
            - name: LISTENER_ADDR
              value: 10.164.0.4 
            - name: LISTENER_PORT
              value: "9001"
            - name: POC_ADDR 
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POC_PORT
              value: "80"
          image: 10.164.0.4:5000/cve-poc
          name: cve-poc
          resources: {}
      hostname: ldapsvr
      restartPolicy: Always
status: {}
